"""add reward_coins to badge

Revision ID: 2b4ea63144dd
Revises: 
Create Date: 2026-03-20 15:56:37.365225
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2b4ea63144dd'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badges', sa.Column('reward_coins', sa.Integer(), server_default='10', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badges', 'reward_coins')
    # ### end Alembic commands ###
