"""Add TTS audio cache table

Revision ID: 573a2bb8a38f
Revises: 2b4ea63144dd
Create Date: 2026-03-25 11:59:15.778586
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '573a2bb8a38f'
down_revision: Union[str, None] = '2b4ea63144dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tts_audio_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text_content', sa.String(length=500), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('voice', sa.String(length=20), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('audio_data', sa.Text(), nullable=False),
    sa.Column('audio_size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tts_audio_cache_text_content'), 'tts_audio_cache', ['text_content'], unique=False)
    op.create_index(op.f('ix_tts_audio_cache_text_hash'), 'tts_audio_cache', ['text_hash'], unique=True)
    op.create_index('ix_tts_cache_text_hash', 'tts_audio_cache', ['text_hash'], unique=False)
    op.create_index('ix_tts_cache_usage', 'tts_audio_cache', ['usage_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tts_cache_usage', table_name='tts_audio_cache')
    op.drop_index('ix_tts_cache_text_hash', table_name='tts_audio_cache')
    op.drop_index(op.f('ix_tts_audio_cache_text_hash'), table_name='tts_audio_cache')
    op.drop_index(op.f('ix_tts_audio_cache_text_content'), table_name='tts_audio_cache')
    op.drop_table('tts_audio_cache')
    # ### end Alembic commands ###
